#! /usr/bin/env bash
set -x

SOLHINT_CHANGED_FILELIST=$(git diff --cached --name-only --diff-filter=ACMR contracts/ | sed 's| |\\ |g')

if [ ! -z "$SOLHINT_CHANGED_FILELIST" ]; then
	npx solhint -f table --disc $CHANGE_FILELIST
fi

CHANGE_FILELIST=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
echo $CHANGE_FILELIST;
if [ ! -z "$CHANGE_FILELIST" ]; then
	npx prettier $CHANGE_FILELIST --check --ignore-unknown
fi
